//! OpportunityItem DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OpportunityItem;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OpportunityItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOpportunityItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "opportunity_id")]
    pub opportunity_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub amount: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OpportunityItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOpportunityItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "opportunity_id")]
    pub opportunity_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub amount: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OpportunityItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOpportunityItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opportunity_id")]
    pub opportunity_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<Decimal>,
}

impl PatchOpportunityItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.opportunity_id.is_some() || self.company_id.is_some() || self.item_id.is_some() || self.description.is_some() || self.quantity.is_some() || self.rate.is_some() || self.amount.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OpportunityItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OpportunityItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub opportunity_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub amount: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OpportunityItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OpportunityItemListResponseDto {
    /// List of items
    pub items: Vec<OpportunityItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OpportunityItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OpportunityItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OpportunityItemSummaryDto {
    pub id: Uuid,
    pub opportunity_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OpportunityItem> for OpportunityItemResponseDto {
    fn from(entity: OpportunityItem) -> Self {
        Self {
            id: entity.id,
            opportunity_id: entity.opportunity_id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            description: entity.description,
            quantity: entity.quantity,
            rate: entity.rate,
            amount: entity.amount,
            metadata: entity.metadata,
        }
    }
}

impl From<OpportunityItem> for OpportunityItemSummaryDto {
    fn from(entity: OpportunityItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            opportunity_id: entity.opportunity_id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            created_at,
        }
    }
}

impl From<CreateOpportunityItemDto> for OpportunityItem {
    fn from(dto: CreateOpportunityItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            opportunity_id: dto.opportunity_id,
            company_id: dto.company_id,
            item_id: dto.item_id,
            description: dto.description,
            quantity: dto.quantity,
            rate: dto.rate,
            amount: dto.amount,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OpportunityItem> for OpportunityItemResponseDto {
    fn from(entity: &OpportunityItem) -> Self {
        Self {
            id: entity.id.clone(),
            opportunity_id: entity.opportunity_id.clone(),
            company_id: entity.company_id.clone(),
            item_id: entity.item_id.clone(),
            description: entity.description.clone(),
            quantity: entity.quantity.clone(),
            rate: entity.rate.clone(),
            amount: entity.amount.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOpportunityItemDto> for OpportunityItem {
    fn from_create_dto(dto: CreateOpportunityItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(OpportunityItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOpportunityItemDto> for OpportunityItem {
    fn apply_update(mut self, dto: UpdateOpportunityItemDto) -> backbone_core::ServiceResult<Self> {
        self.opportunity_id = dto.opportunity_id;
        self.company_id = dto.company_id;
        self.item_id = dto.item_id;
        self.description = dto.description;
        self.quantity = dto.quantity;
        self.rate = dto.rate;
        self.amount = dto.amount;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OpportunityItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
