//! Opportunity DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Opportunity;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::OpportunityStatus;
use crate::domain::entity::SalesStage;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Opportunity
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOpportunityDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "opportunity_name")]
    pub opportunity_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "lead_id")]
    pub lead_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "expected_amount")]
    pub expected_amount: Decimal,
    #[serde(alias = "sales_stage")]
    pub sales_stage: SalesStage,
    pub probability: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expected_close_date")]
    pub expected_close_date: Option<DateTime<Utc>>,
    pub status: OpportunityStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "quotation_id")]
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "lost_reason")]
    pub lost_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub competitor: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Opportunity
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOpportunityDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "opportunity_name")]
    pub opportunity_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "lead_id")]
    pub lead_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "expected_amount")]
    pub expected_amount: Decimal,
    #[serde(alias = "sales_stage")]
    pub sales_stage: SalesStage,
    pub probability: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expected_close_date")]
    pub expected_close_date: Option<DateTime<Utc>>,
    pub status: OpportunityStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "quotation_id")]
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "lost_reason")]
    pub lost_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub competitor: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Opportunity
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOpportunityDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opportunity_name")]
    pub opportunity_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "lead_id")]
    pub lead_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expected_amount")]
    pub expected_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sales_stage")]
    pub sales_stage: Option<SalesStage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub probability: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expected_close_date")]
    pub expected_close_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<OpportunityStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "quotation_id")]
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "lost_reason")]
    pub lost_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub competitor: Option<String>,
}

impl PatchOpportunityDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.opportunity_name.is_some() || self.lead_id.is_some() || self.party_id.is_some() || self.campaign_id.is_some() || self.currency.is_some() || self.expected_amount.is_some() || self.sales_stage.is_some() || self.probability.is_some() || self.expected_close_date.is_some() || self.status.is_some() || self.quotation_id.is_some() || self.lost_reason.is_some() || self.competitor.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Opportunity entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OpportunityResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub opportunity_name: String,
    pub lead_id: Option<Uuid>,
    pub party_id: Option<Uuid>,
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub expected_amount: Decimal,
    pub sales_stage: SalesStage,
    pub probability: Decimal,
    pub expected_close_date: Option<DateTime<Utc>>,
    pub status: OpportunityStatus,
    pub quotation_id: Option<Uuid>,
    pub lost_reason: Option<String>,
    pub competitor: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Opportunity entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OpportunityListResponseDto {
    /// List of items
    pub items: Vec<OpportunityResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OpportunityListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OpportunityResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OpportunitySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub opportunity_name: String,
    pub lead_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Opportunity> for OpportunityResponseDto {
    fn from(entity: Opportunity) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            opportunity_name: entity.opportunity_name,
            lead_id: entity.lead_id,
            party_id: entity.party_id,
            campaign_id: entity.campaign_id,
            currency: entity.currency,
            expected_amount: entity.expected_amount,
            sales_stage: entity.sales_stage,
            probability: entity.probability,
            expected_close_date: entity.expected_close_date,
            status: entity.status,
            quotation_id: entity.quotation_id,
            lost_reason: entity.lost_reason,
            competitor: entity.competitor,
            metadata: entity.metadata,
        }
    }
}

impl From<Opportunity> for OpportunitySummaryDto {
    fn from(entity: Opportunity) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            opportunity_name: entity.opportunity_name,
            lead_id: entity.lead_id,
            created_at,
        }
    }
}

impl From<CreateOpportunityDto> for Opportunity {
    fn from(dto: CreateOpportunityDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            opportunity_name: dto.opportunity_name,
            lead_id: dto.lead_id,
            party_id: dto.party_id,
            campaign_id: dto.campaign_id,
            currency: dto.currency,
            expected_amount: dto.expected_amount,
            sales_stage: dto.sales_stage,
            probability: dto.probability,
            expected_close_date: dto.expected_close_date,
            status: dto.status,
            quotation_id: dto.quotation_id,
            lost_reason: dto.lost_reason,
            competitor: dto.competitor,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Opportunity> for OpportunityResponseDto {
    fn from(entity: &Opportunity) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            opportunity_name: entity.opportunity_name.clone(),
            lead_id: entity.lead_id.clone(),
            party_id: entity.party_id.clone(),
            campaign_id: entity.campaign_id.clone(),
            currency: entity.currency.clone(),
            expected_amount: entity.expected_amount.clone(),
            sales_stage: entity.sales_stage.clone(),
            probability: entity.probability.clone(),
            expected_close_date: entity.expected_close_date.clone(),
            status: entity.status.clone(),
            quotation_id: entity.quotation_id.clone(),
            lost_reason: entity.lost_reason.clone(),
            competitor: entity.competitor.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOpportunityDto> for Opportunity {
    fn from_create_dto(dto: CreateOpportunityDto) -> backbone_core::ServiceResult<Self> {
        Ok(Opportunity::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOpportunityDto> for Opportunity {
    fn apply_update(mut self, dto: UpdateOpportunityDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.opportunity_name = dto.opportunity_name;
        self.lead_id = dto.lead_id;
        self.party_id = dto.party_id;
        self.campaign_id = dto.campaign_id;
        self.currency = dto.currency;
        self.expected_amount = dto.expected_amount;
        self.sales_stage = dto.sales_stage;
        self.probability = dto.probability;
        self.expected_close_date = dto.expected_close_date;
        self.status = dto.status;
        self.quotation_id = dto.quotation_id;
        self.lost_reason = dto.lost_reason;
        self.competitor = dto.competitor;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Opportunity here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
