//! Domain policy for Campaign aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Campaign;

/// Domain policy for Campaign — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Campaign>` in the `// <<< CUSTOM` zone.
pub type CampaignDomainPolicy = PermitAllPolicy<Campaign>;

// <<< CUSTOM
// END CUSTOM
