//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod campaign_domain_policy;
pub mod opportunity_domain_policy;
pub mod opportunity_item_domain_policy;

pub use campaign_domain_policy::CampaignDomainPolicy;
pub use opportunity_domain_policy::OpportunityDomainPolicy;
pub use opportunity_item_domain_policy::OpportunityItemDomainPolicy;

// <<< CUSTOM
// END CUSTOM
