//! Application service for Campaign entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `campaign_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCampaignDto, UpdateCampaignDto};
use crate::domain::entity::Campaign;
use crate::infrastructure::persistence::CampaignRepository;

/// Application service for Campaign entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `campaign_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CampaignServiceCustom {
///     inner: Arc<CampaignService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CampaignService = GenericCrudService<
    Campaign,
    CreateCampaignDto,
    UpdateCampaignDto,
    CampaignRepository,
>;

// <<< CUSTOM
// END CUSTOM
