//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod campaign_service;
pub mod opportunity_service;
pub mod opportunity_item_service;

// <<< CUSTOM
pub mod deal_ports;
pub mod deal_write_service;
// END CUSTOM

pub use campaign_service::CampaignService;
pub use opportunity_service::OpportunityService;
pub use opportunity_item_service::OpportunityItemService;
// <<< CUSTOM
pub use deal_ports::{SellingPort, QuotationFromOpp, OppLine, QuotationAck, CrmRejected};
pub use deal_write_service::{DealWriteService, WinOutcome, DealError};
// END CUSTOM