//! Application service for Opportunity entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `opportunity_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOpportunityDto, UpdateOpportunityDto};
use crate::domain::entity::Opportunity;
use crate::infrastructure::persistence::OpportunityRepository;

/// Application service for Opportunity entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `opportunity_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OpportunityServiceCustom {
///     inner: Arc<OpportunityService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OpportunityService = GenericCrudService<
    Opportunity,
    CreateOpportunityDto,
    UpdateOpportunityDto,
    OpportunityRepository,
>;

// <<< CUSTOM
// END CUSTOM
