-- OpportunityItem Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the deal.opportunity_items table.
-- Customize this file to add your initial data.

-- INSERT INTO deal.opportunity_items (
--     id,
--     opportunity_id,
--     company_id,
--     item_id,
--     description,
--     quantity,
--     rate,
--     amount,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO deal.opportunity_items (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

