-- Opportunity Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the deal.opportunities table.
-- Customize this file to add your initial data.

-- INSERT INTO deal.opportunities (
--     id,
--     company_id,
--     opportunity_name,
--     lead_id,
--     party_id,
--     campaign_id,
--     currency,
--     expected_amount,
--     sales_stage,
--     probability,
--     expected_close_date,
--     status,
--     quotation_id,
--     lost_reason,
--     competitor,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO deal.opportunities (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

