-- Migration: Create opportunity_items table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS deal;

CREATE TABLE IF NOT EXISTS deal.opportunity_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    opportunity_id UUID NOT NULL,
    company_id UUID NOT NULL,
    item_id UUID NOT NULL,
    description TEXT,
    quantity NUMERIC(18, 4) NOT NULL,
    rate NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (rate >= 0),
    amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_opportunity_items_opportunity_id ON deal.opportunity_items (opportunity_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_opportunity_items_metadata_gin ON deal.opportunity_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_opportunity_items_metadata_deleted_at ON deal.opportunity_items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_opportunity_items_metadata_created_at ON deal.opportunity_items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_opportunity_items_metadata_updated_at ON deal.opportunity_items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION deal.opportunity_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS opportunity_items_insert_audit ON deal.opportunity_items;
CREATE TRIGGER opportunity_items_insert_audit BEFORE INSERT ON deal.opportunity_items
    FOR EACH ROW EXECUTE FUNCTION deal.opportunity_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS opportunity_items_update_audit ON deal.opportunity_items;
CREATE TRIGGER opportunity_items_update_audit BEFORE UPDATE ON deal.opportunity_items
    FOR EACH ROW EXECUTE FUNCTION deal.opportunity_items_audit_timestamp();
