-- Audit Triggers Migration for deal module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Campaign (deal.campaigns)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION deal.campaigns_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS campaigns_insert_audit ON deal.campaigns;
CREATE TRIGGER campaigns_insert_audit BEFORE INSERT ON deal.campaigns
    FOR EACH ROW EXECUTE FUNCTION deal.campaigns_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS campaigns_update_audit ON deal.campaigns;
CREATE TRIGGER campaigns_update_audit BEFORE UPDATE ON deal.campaigns
    FOR EACH ROW EXECUTE FUNCTION deal.campaigns_audit_timestamp();

-- ==============================================================================
-- Table: Opportunity (deal.opportunities)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION deal.opportunities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS opportunities_insert_audit ON deal.opportunities;
CREATE TRIGGER opportunities_insert_audit BEFORE INSERT ON deal.opportunities
    FOR EACH ROW EXECUTE FUNCTION deal.opportunities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS opportunities_update_audit ON deal.opportunities;
CREATE TRIGGER opportunities_update_audit BEFORE UPDATE ON deal.opportunities
    FOR EACH ROW EXECUTE FUNCTION deal.opportunities_audit_timestamp();

-- ==============================================================================
-- Table: OpportunityItem (deal.opportunity_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION deal.opportunity_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS opportunity_items_insert_audit ON deal.opportunity_items;
CREATE TRIGGER opportunity_items_insert_audit BEFORE INSERT ON deal.opportunity_items
    FOR EACH ROW EXECUTE FUNCTION deal.opportunity_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS opportunity_items_update_audit ON deal.opportunity_items;
CREATE TRIGGER opportunity_items_update_audit BEFORE UPDATE ON deal.opportunity_items
    FOR EACH ROW EXECUTE FUNCTION deal.opportunity_items_audit_timestamp();

