-- Migration: Create opportunities table
-- Generated by metaphor-schema

-- Create sales_stage enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_stage') THEN
        CREATE TYPE sales_stage AS ENUM ('prospecting', 'qualification', 'proposal', 'negotiation', 'closing');
    END IF;
END
$$;

-- Create opportunity_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'opportunity_status') THEN
        CREATE TYPE opportunity_status AS ENUM ('open', 'won', 'lost');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS deal;

CREATE TABLE IF NOT EXISTS deal.opportunities (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    opportunity_name TEXT NOT NULL,
    lead_id UUID,
    party_id UUID,
    campaign_id UUID,
    currency TEXT NOT NULL DEFAULT 'IDR',
    expected_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (expected_amount >= 0),
    sales_stage sales_stage NOT NULL DEFAULT 'prospecting',
    probability NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (probability >= 0),
    expected_close_date TIMESTAMPTZ,
    status opportunity_status NOT NULL DEFAULT 'open',
    quotation_id UUID,
    lost_reason TEXT,
    competitor TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_opportunities_company_id_status_sales_stage ON deal.opportunities (company_id, status, sales_stage);

CREATE INDEX IF NOT EXISTS idx_opportunities_lead_id ON deal.opportunities (lead_id);

CREATE INDEX IF NOT EXISTS idx_opportunities_party_id ON deal.opportunities (party_id);

CREATE INDEX IF NOT EXISTS idx_opportunities_campaign_id ON deal.opportunities (campaign_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_opportunities_metadata_gin ON deal.opportunities USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_opportunities_metadata_deleted_at ON deal.opportunities ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_opportunities_metadata_created_at ON deal.opportunities ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_opportunities_metadata_updated_at ON deal.opportunities ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION deal.opportunities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS opportunities_insert_audit ON deal.opportunities;
CREATE TRIGGER opportunities_insert_audit BEFORE INSERT ON deal.opportunities
    FOR EACH ROW EXECUTE FUNCTION deal.opportunities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS opportunities_update_audit ON deal.opportunities;
CREATE TRIGGER opportunities_update_audit BEFORE UPDATE ON deal.opportunities
    FOR EACH ROW EXECUTE FUNCTION deal.opportunities_audit_timestamp();
