-- Enum types for deal module
-- Generated by metaphor-schema

-- Create sales_stage enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_stage') THEN
        CREATE TYPE sales_stage AS ENUM ('prospecting', 'qualification', 'proposal', 'negotiation', 'closing');
    END IF;
END
$$;

-- Create opportunity_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'opportunity_status') THEN
        CREATE TYPE opportunity_status AS ENUM ('open', 'won', 'lost');
    END IF;
END
$$;

