-- Migration: Create stages table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS deal;

CREATE TABLE IF NOT EXISTS deal.stages (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 10 CHECK (sequence >= 0),
    is_won BOOLEAN NOT NULL DEFAULT FALSE,
    probability_hint NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (probability_hint >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_stages_company_id_code ON deal.stages (company_id, code);

CREATE UNIQUE INDEX IF NOT EXISTS idx_stages_company_id_name ON deal.stages (company_id, name);

CREATE INDEX IF NOT EXISTS idx_stages_company_id_sequence ON deal.stages (company_id, sequence);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_stages_metadata_gin ON deal.stages USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_stages_metadata_deleted_at ON deal.stages ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_stages_metadata_created_at ON deal.stages ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_stages_metadata_updated_at ON deal.stages ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION deal.stages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS stages_insert_audit ON deal.stages;
CREATE TRIGGER stages_insert_audit BEFORE INSERT ON deal.stages
    FOR EACH ROW EXECUTE FUNCTION deal.stages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS stages_update_audit ON deal.stages;
CREATE TRIGGER stages_update_audit BEFORE UPDATE ON deal.stages
    FOR EACH ROW EXECUTE FUNCTION deal.stages_audit_timestamp();
