-- Company RLS fence for deal module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for deal.campaigns
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE deal.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal.campaigns FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS campaigns_company_isolation ON deal.campaigns;
CREATE POLICY campaigns_company_isolation ON deal.campaigns
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for deal.opportunities
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE deal.opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal.opportunities FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS opportunities_company_isolation ON deal.opportunities;
CREATE POLICY opportunities_company_isolation ON deal.opportunities
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for deal.opportunity_items
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE deal.opportunity_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal.opportunity_items FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS opportunity_items_company_isolation ON deal.opportunity_items;
CREATE POLICY opportunity_items_company_isolation ON deal.opportunity_items
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

