//! Domain events for Campaign entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Campaign;

/// Domain events for Campaign — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Campaign>)` variant.
pub type CampaignEvent = CrudEvent<Campaign>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Campaign events.
pub type CampaignEventPublisher = Arc<dyn CrudEventPublisher<Campaign> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCampaignEventPublisher = NoOpCrudEventPublisher<Campaign>;
