//! Event handler trait for Campaign events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CampaignEvent;

/// Event handler for Campaign events.
/// Implement this trait to react to Campaign lifecycle events.
pub trait CampaignEventHandler: EventHandler<CampaignEvent> {}
