//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod campaign_events;
pub mod campaign_event_handlers;
pub mod opportunity_events;
pub mod opportunity_event_handlers;
pub mod opportunity_item_events;
pub mod opportunity_item_event_handlers;

pub use campaign_events::{CampaignEvent, CampaignEventPublisher, NoopCampaignEventPublisher};
pub use campaign_event_handlers::CampaignEventHandler;
pub use opportunity_events::{OpportunityEvent, OpportunityEventPublisher, NoopOpportunityEventPublisher};
pub use opportunity_event_handlers::OpportunityEventHandler;
pub use opportunity_item_events::{OpportunityItemEvent, OpportunityItemEventPublisher, NoopOpportunityItemEventPublisher};
pub use opportunity_item_event_handlers::OpportunityItemEventHandler;

// <<< CUSTOM
pub mod deal_outcome_events;
pub use deal_outcome_events::{
    OpportunityWon, OpportunityLost, DealEvent, DealEventSink, LoggingDealSink,
};
// END CUSTOM