//! Event handler trait for Opportunity events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OpportunityEvent;

/// Event handler for Opportunity events.
/// Implement this trait to react to Opportunity lifecycle events.
pub trait OpportunityEventHandler: EventHandler<OpportunityEvent> {}
