//! Event handler trait for OpportunityItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OpportunityItemEvent;

/// Event handler for OpportunityItem events.
/// Implement this trait to react to OpportunityItem lifecycle events.
pub trait OpportunityItemEventHandler: EventHandler<OpportunityItemEvent> {}
