//! Domain events for OpportunityItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OpportunityItem;

/// Domain events for OpportunityItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OpportunityItem>)` variant.
pub type OpportunityItemEvent = CrudEvent<OpportunityItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OpportunityItem events.
pub type OpportunityItemEventPublisher = Arc<dyn CrudEventPublisher<OpportunityItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOpportunityItemEventPublisher = NoOpCrudEventPublisher<OpportunityItem>;
