//! Domain events for Opportunity entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Opportunity;

/// Domain events for Opportunity — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Opportunity>)` variant.
pub type OpportunityEvent = CrudEvent<Opportunity>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Opportunity events.
pub type OpportunityEventPublisher = Arc<dyn CrudEventPublisher<Opportunity> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOpportunityEventPublisher = NoOpCrudEventPublisher<Opportunity>;
