//! Campaign seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Campaign data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CAMPAIGN SEEDER
// ============================================================================

/// Seeder for campaign
pub struct SeedCampaignSeeder;

impl SeedCampaignSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCampaignSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCampaignSeeder {
    fn name(&self) -> &'static str {
        "SeedCampaignSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if deal.campaigns table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM deal.campaigns")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/campaign_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM deal.campaigns")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

