//! OpportunityItem seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial OpportunityItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// OPPORTUNITYITEM SEEDER
// ============================================================================

/// Seeder for opportunity_item
pub struct SeedOpportunityItemSeeder;

impl SeedOpportunityItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedOpportunityItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedOpportunityItemSeeder {
    fn name(&self) -> &'static str {
        "SeedOpportunityItemSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if deal.opportunity_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM deal.opportunity_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/opportunity_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM deal.opportunity_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

