//! Repository trait for Campaign aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Campaign aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Campaign;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CampaignPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CampaignPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CampaignPaginatedResult {
    pub data: Vec<Campaign>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CampaignFilter {
    pub company_id: Option<Uuid>,
    pub campaign_name: Option<String>,
    pub utm_source: Option<String>,
    pub utm_medium: Option<String>,
    pub utm_campaign: Option<String>,
    pub is_active: Option<bool>,
}

impl CampaignFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.campaign_name.is_some() || self.utm_source.is_some() || self.utm_medium.is_some() || self.utm_campaign.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for Campaign aggregate
///
/// This trait defines the persistence contract for Campaign entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CampaignRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new campaign entity
    async fn save(&self, entity: &Campaign) -> Result<Campaign>;

    /// Find campaign by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Campaign>>;

    /// Find all campaign entities
    async fn find_all(&self) -> Result<Vec<Campaign>>;

    /// Update campaign by ID
    async fn update(&self, id: &str, entity: &Campaign) -> Result<Option<Campaign>>;

    /// Delete campaign by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List campaign with pagination
    async fn list(&self, params: CampaignPaginationParams) -> Result<CampaignPaginatedResult>;

    /// List campaign with pagination and filters
    async fn list_with_filters(&self, params: CampaignPaginationParams, filters: CampaignFilter) -> Result<CampaignPaginatedResult>;

    /// Count all campaign entities
    async fn count(&self) -> Result<u64>;

    /// Count campaign entities matching filters
    async fn count_with_filters(&self, filters: CampaignFilter) -> Result<u64>;

    /// Check if campaign exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete campaign by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted campaign by ID
    async fn restore(&self, id: &str) -> Result<Option<Campaign>>;

    /// List soft-deleted campaign entities
    async fn list_deleted(&self, params: CampaignPaginationParams) -> Result<CampaignPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save campaign entities
    async fn bulk_save(&self, entities: &[Campaign]) -> Result<Vec<Campaign>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
