//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod campaign_repository;
pub mod opportunity_repository;
pub mod opportunity_item_repository;

// Re-exports
pub use campaign_repository::{
    CampaignRepository,
    CampaignPaginationParams,
    CampaignPaginatedResult,
    CampaignFilter,
};
pub use opportunity_repository::{
    OpportunityRepository,
    OpportunityPaginationParams,
    OpportunityPaginatedResult,
    OpportunityFilter,
};
pub use opportunity_item_repository::{
    OpportunityItemRepository,
    OpportunityItemPaginationParams,
    OpportunityItemPaginatedResult,
    OpportunityItemFilter,
};
