//! Repository trait for OpportunityItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OpportunityItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::OpportunityItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OpportunityItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OpportunityItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OpportunityItemPaginatedResult {
    pub data: Vec<OpportunityItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OpportunityItemFilter {
    pub opportunity_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub description: Option<String>,
}

impl OpportunityItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.opportunity_id.is_some() || self.company_id.is_some() || self.item_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for OpportunityItem aggregate
///
/// This trait defines the persistence contract for OpportunityItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OpportunityItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new opportunity_item entity
    async fn save(&self, entity: &OpportunityItem) -> Result<OpportunityItem>;

    /// Find opportunity_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OpportunityItem>>;

    /// Find all opportunity_item entities
    async fn find_all(&self) -> Result<Vec<OpportunityItem>>;

    /// Update opportunity_item by ID
    async fn update(&self, id: &str, entity: &OpportunityItem) -> Result<Option<OpportunityItem>>;

    /// Delete opportunity_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List opportunity_item with pagination
    async fn list(&self, params: OpportunityItemPaginationParams) -> Result<OpportunityItemPaginatedResult>;

    /// List opportunity_item with pagination and filters
    async fn list_with_filters(&self, params: OpportunityItemPaginationParams, filters: OpportunityItemFilter) -> Result<OpportunityItemPaginatedResult>;

    /// Count all opportunity_item entities
    async fn count(&self) -> Result<u64>;

    /// Count opportunity_item entities matching filters
    async fn count_with_filters(&self, filters: OpportunityItemFilter) -> Result<u64>;

    /// Check if opportunity_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete opportunity_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted opportunity_item by ID
    async fn restore(&self, id: &str) -> Result<Option<OpportunityItem>>;

    /// List soft-deleted opportunity_item entities
    async fn list_deleted(&self, params: OpportunityItemPaginationParams) -> Result<OpportunityItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save opportunity_item entities
    async fn bulk_save(&self, entities: &[OpportunityItem]) -> Result<Vec<OpportunityItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
