//! Repository trait for Opportunity aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Opportunity aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Opportunity, OpportunityStatus, SalesStage};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OpportunityPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OpportunityPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OpportunityPaginatedResult {
    pub data: Vec<Opportunity>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OpportunityFilter {
    pub company_id: Option<Uuid>,
    pub opportunity_name: Option<String>,
    pub lead_id: Option<Uuid>,
    pub party_id: Option<Uuid>,
    pub campaign_id: Option<Uuid>,
    pub currency: Option<String>,
    pub sales_stage: Option<SalesStage>,
    pub status: Option<OpportunityStatus>,
    pub quotation_id: Option<Uuid>,
    pub lost_reason: Option<String>,
    pub competitor: Option<String>,
}

impl OpportunityFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.opportunity_name.is_some() || self.lead_id.is_some() || self.party_id.is_some() || self.campaign_id.is_some() || self.currency.is_some() || self.sales_stage.is_some() || self.status.is_some() || self.quotation_id.is_some() || self.lost_reason.is_some() || self.competitor.is_some()
    }
}

/// Repository trait for Opportunity aggregate
///
/// This trait defines the persistence contract for Opportunity entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OpportunityRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new opportunity entity
    async fn save(&self, entity: &Opportunity) -> Result<Opportunity>;

    /// Find opportunity by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Opportunity>>;

    /// Find all opportunity entities
    async fn find_all(&self) -> Result<Vec<Opportunity>>;

    /// Update opportunity by ID
    async fn update(&self, id: &str, entity: &Opportunity) -> Result<Option<Opportunity>>;

    /// Delete opportunity by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List opportunity with pagination
    async fn list(&self, params: OpportunityPaginationParams) -> Result<OpportunityPaginatedResult>;

    /// List opportunity with pagination and filters
    async fn list_with_filters(&self, params: OpportunityPaginationParams, filters: OpportunityFilter) -> Result<OpportunityPaginatedResult>;

    /// Count all opportunity entities
    async fn count(&self) -> Result<u64>;

    /// Count opportunity entities matching filters
    async fn count_with_filters(&self, filters: OpportunityFilter) -> Result<u64>;

    /// Check if opportunity exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete opportunity by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted opportunity by ID
    async fn restore(&self, id: &str) -> Result<Option<Opportunity>>;

    /// List soft-deleted opportunity entities
    async fn list_deleted(&self, params: OpportunityPaginationParams) -> Result<OpportunityPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save opportunity entities
    async fn bulk_save(&self, entities: &[Opportunity]) -> Result<Vec<Opportunity>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
