//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod campaign_repository;
mod opportunity_repository;
mod opportunity_item_repository;
mod stage_repository;

// Custom persistence modules
// <<< CUSTOM
pub use opportunity_repository::{
    DEFAULT_STAGES, NewOpportunityRow, OpportunityForWinRow, StageMoveRow, StageProbeRow,
};
pub use opportunity_item_repository::{NewOppItemRow, OppItemLineRow};
// END CUSTOM

// Re-exports
pub use campaign_repository::CampaignRepository;
pub use opportunity_repository::OpportunityRepository;
pub use opportunity_item_repository::OpportunityItemRepository;
pub use stage_repository::StageRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
