//! Validator for Campaign entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Campaign>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Campaign;

/// Validator type alias for Campaign entities.
pub type CampaignValidator = EntityValidator<Campaign>;

/// Build a validator for Campaign with all schema-defined field rules.
pub fn campaign_validator() -> CampaignValidator {
    EntityValidator::new()
        .rule(RequiredString::new("campaign_name", |e: &Campaign| &e.campaign_name))
        .rule(OptionalNotBlank::new("utm_source", |e: &Campaign| e.utm_source.as_deref()))
        .rule(OptionalNotBlank::new("utm_medium", |e: &Campaign| e.utm_medium.as_deref()))
        .rule(OptionalNotBlank::new("utm_campaign", |e: &Campaign| e.utm_campaign.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
