//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod campaign_validator;
pub mod opportunity_validator;
pub mod opportunity_item_validator;

pub use campaign_validator::{CampaignValidator, campaign_validator};
pub use opportunity_validator::{OpportunityValidator, opportunity_validator};
pub use opportunity_item_validator::{OpportunityItemValidator, opportunity_item_validator};

// <<< CUSTOM
// END CUSTOM
