//! Validator for Opportunity entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Opportunity>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Opportunity;

/// Validator type alias for Opportunity entities.
pub type OpportunityValidator = EntityValidator<Opportunity>;

/// Build a validator for Opportunity with all schema-defined field rules.
pub fn opportunity_validator() -> OpportunityValidator {
    EntityValidator::new()
        .rule(RequiredString::new("opportunity_name", |e: &Opportunity| &e.opportunity_name))
        .rule(RequiredString::new("currency", |e: &Opportunity| &e.currency))
        .rule(OptionalNotBlank::new("lost_reason", |e: &Opportunity| e.lost_reason.as_deref()))
        .rule(OptionalNotBlank::new("competitor", |e: &Opportunity| e.competitor.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
