//! Validator for OpportunityItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OpportunityItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::OpportunityItem;

/// Validator type alias for OpportunityItem entities.
pub type OpportunityItemValidator = EntityValidator<OpportunityItem>;

/// Build a validator for OpportunityItem with all schema-defined field rules.
pub fn opportunity_item_validator() -> OpportunityItemValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("description", |e: &OpportunityItem| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
