//! Campaign API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Campaign CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CAMPAIGN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Campaign
pub struct CampaignTestData;

impl TestDataGenerator for CampaignTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "campaign_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "utm_source": null,
            "utm_medium": null,
            "utm_campaign": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "campaign_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "utm_source": null,
            "utm_medium": null,
            "utm_campaign": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CAMPAIGN API TEST
// ============================================================================

/// Campaign API test suite
pub struct CampaignApiTest {
    inner: GenericCrudTest<CampaignTestData>,
}

impl CampaignApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/campaigns", "Campaign");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CampaignTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CampaignApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_campaign_crud() {
        let mut test = CampaignApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Campaign specific tests here
// <<< CUSTOM TESTS END >>>
