//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod campaign_api_test;
pub mod opportunity_api_test;
pub mod opportunity_item_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use campaign_api_test::*;
pub use opportunity_api_test::*;
pub use opportunity_item_api_test::*;
