//! Opportunity API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Opportunity CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// OPPORTUNITY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Opportunity
pub struct OpportunityTestData;

impl TestDataGenerator for OpportunityTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "opportunity_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "lead_id": null,
            "party_id": null,
            "campaign_id": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "expected_amount": 0,
            "sales_stage": "prospecting",
            "probability": 0,
            "expected_close_date": null,
            "status": "open",
            "quotation_id": null,
            "lost_reason": null,
            "competitor": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "opportunity_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "lead_id": null,
            "party_id": null,
            "campaign_id": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "expected_amount": 0,
            "sales_stage": "prospecting",
            "probability": 0,
            "expected_close_date": null,
            "status": "open",
            "quotation_id": null,
            "lost_reason": null,
            "competitor": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// OPPORTUNITY API TEST
// ============================================================================

/// Opportunity API test suite
pub struct OpportunityApiTest {
    inner: GenericCrudTest<OpportunityTestData>,
}

impl OpportunityApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/opportunities", "Opportunity");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, OpportunityTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OpportunityApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_opportunity_crud() {
        let mut test = OpportunityApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Opportunity specific tests here
// <<< CUSTOM TESTS END >>>
