//! Deal Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CampaignService;
use crate::application::service::OpportunityService;
use crate::application::service::OpportunityItemService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Campaign service
    pub campaign_service: Arc<CampaignService>,
    /// Opportunity service
    pub opportunity_service: Arc<OpportunityService>,
    /// OpportunityItem service
    pub opportunity_item_service: Arc<OpportunityItemService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        campaign_service: Arc<CampaignService>,
        opportunity_service: Arc<OpportunityService>,
        opportunity_item_service: Arc<OpportunityItemService>
    ) -> Self {
        Self {
            campaign_service,
            opportunity_service,
            opportunity_item_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::DealModule) -> Self {
        Self {
            campaign_service: module.campaign_service.clone(),
            opportunity_service: module.opportunity_service.clone(),
            opportunity_item_service: module.opportunity_item_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    campaign_service: Option<Arc<CampaignService>>,
    opportunity_service: Option<Arc<OpportunityService>>,
    opportunity_item_service: Option<Arc<OpportunityItemService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Campaign service.
    pub fn with_campaign_service(mut self, service: Arc<CampaignService>) -> Self {
        self.campaign_service = Some(service);
        self
    }

    /// Set the Opportunity service.
    pub fn with_opportunity_service(mut self, service: Arc<OpportunityService>) -> Self {
        self.opportunity_service = Some(service);
        self
    }

    /// Set the OpportunityItem service.
    pub fn with_opportunity_item_service(mut self, service: Arc<OpportunityItemService>) -> Self {
        self.opportunity_item_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            campaign_service: self.campaign_service.expect("campaign_service is required"),
            opportunity_service: self.opportunity_service.expect("opportunity_service is required"),
            opportunity_item_service: self.opportunity_item_service.expect("opportunity_item_service is required"),
        }
    }
}
