//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    campaign_handler::create_campaign_routes,
    opportunity_handler::create_opportunity_routes,
    opportunity_item_handler::create_opportunity_item_routes,
};

use crate::application::service::{
    CampaignService,
    OpportunityService,
    OpportunityItemService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub campaign: Arc<CampaignService>,
    pub opportunity: Arc<OpportunityService>,
    pub opportunity_item: Arc<OpportunityItemService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Campaign routes (12 Backbone endpoints)
        .merge(create_campaign_routes(services.campaign))
        // Opportunity routes (12 Backbone endpoints)
        .merge(create_opportunity_routes(services.opportunity))
        // OpportunityItem routes (12 Backbone endpoints)
        .merge(create_opportunity_item_routes(services.opportunity_item))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn campaign_routes(service: Arc<CampaignService>) -> Router {
        create_campaign_routes(service)
    }

    pub fn opportunity_routes(service: Arc<OpportunityService>) -> Router {
        create_opportunity_routes(service)
    }

    pub fn opportunity_item_routes(service: Arc<OpportunityItemService>) -> Router {
        create_opportunity_item_routes(service)
    }

}
