//! Public events for Deal module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CAMPAIGN EVENTS
// ============================================================================

/// Event published when a Campaign is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CampaignCreatedEvent {
    pub id: CampaignId,
    pub data: CampaignDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Campaign is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CampaignUpdatedEvent {
    pub id: CampaignId,
    pub data: CampaignDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Campaign is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CampaignDeletedEvent {
    pub id: CampaignId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// OPPORTUNITY EVENTS
// ============================================================================

/// Event published when a Opportunity is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpportunityCreatedEvent {
    pub id: OpportunityId,
    pub data: OpportunityDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Opportunity is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpportunityUpdatedEvent {
    pub id: OpportunityId,
    pub data: OpportunityDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Opportunity is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpportunityDeletedEvent {
    pub id: OpportunityId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// OPPORTUNITYITEM EVENTS
// ============================================================================

/// Event published when a OpportunityItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpportunityItemCreatedEvent {
    pub id: OpportunityItemId,
    pub data: OpportunityItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OpportunityItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpportunityItemUpdatedEvent {
    pub id: OpportunityItemId,
    pub data: OpportunityItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OpportunityItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpportunityItemDeletedEvent {
    pub id: OpportunityItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Deal module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DealEvent {
    CampaignCreated(CampaignCreatedEvent),
    CampaignUpdated(CampaignUpdatedEvent),
    CampaignDeleted(CampaignDeletedEvent),
    OpportunityCreated(OpportunityCreatedEvent),
    OpportunityUpdated(OpportunityUpdatedEvent),
    OpportunityDeleted(OpportunityDeletedEvent),
    OpportunityItemCreated(OpportunityItemCreatedEvent),
    OpportunityItemUpdated(OpportunityItemUpdatedEvent),
    OpportunityItemDeleted(OpportunityItemDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DealEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for DealEventMetadata {
    fn default() -> Self {
        Self {
            module: "deal",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
