//! Deal Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Deal exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use deal::exports::{CampaignDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CampaignDto` - Data transfer object for Campaign
/// - `CampaignSummary` - Summary view of Campaign
/// - `CampaignId` - Type-safe ID wrapper
/// - `OpportunityDto` - Data transfer object for Opportunity
/// - `OpportunitySummary` - Summary view of Opportunity
/// - `OpportunityId` - Type-safe ID wrapper
/// - `OpportunityItemDto` - Data transfer object for OpportunityItem
/// - `OpportunityItemSummary` - Summary view of OpportunityItem
/// - `OpportunityItemId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `CampaignCreatedEvent` - Published when Campaign is created
/// - `CampaignUpdatedEvent` - Published when Campaign is updated
/// - `CampaignDeletedEvent` - Published when Campaign is deleted
/// - `OpportunityCreatedEvent` - Published when Opportunity is created
/// - `OpportunityUpdatedEvent` - Published when Opportunity is updated
/// - `OpportunityDeletedEvent` - Published when Opportunity is deleted
/// - `OpportunityItemCreatedEvent` - Published when OpportunityItem is created
/// - `OpportunityItemUpdatedEvent` - Published when OpportunityItem is updated
/// - `OpportunityItemDeletedEvent` - Published when OpportunityItem is deleted
pub struct ExportSummary;
