//! Public services for Deal module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Deal module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait DealQueryService: Send + Sync {
    /// Get Campaign by ID
    async fn get_campaign(&self, id: CampaignId) -> Result<Option<CampaignDto>>;

    /// Get Campaign summary by ID
    async fn get_campaign_summary(&self, id: CampaignId) -> Result<Option<CampaignSummary>>;

    /// Check if Campaign exists
    async fn campaign_exists(&self, id: CampaignId) -> Result<bool>;

    /// Get Opportunity by ID
    async fn get_opportunity(&self, id: OpportunityId) -> Result<Option<OpportunityDto>>;

    /// Get Opportunity summary by ID
    async fn get_opportunity_summary(&self, id: OpportunityId) -> Result<Option<OpportunitySummary>>;

    /// Check if Opportunity exists
    async fn opportunity_exists(&self, id: OpportunityId) -> Result<bool>;

    /// Get OpportunityItem by ID
    async fn get_opportunity_item(&self, id: OpportunityItemId) -> Result<Option<OpportunityItemDto>>;

    /// Get OpportunityItem summary by ID
    async fn get_opportunity_item_summary(&self, id: OpportunityItemId) -> Result<Option<OpportunityItemSummary>>;

    /// Check if OpportunityItem exists
    async fn opportunity_item_exists(&self, id: OpportunityItemId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
