//! Deal Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CampaignService;
pub use application::service::OpportunityService;
pub use application::service::OpportunityItemService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Deal module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let deal = DealModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = deal.all_crud_routes();
/// ```
pub struct DealModule {
    pub(crate) campaign_service: Arc<CampaignService>,
    pub(crate) opportunity_service: Arc<OpportunityService>,
    pub(crate) opportunity_item_service: Arc<OpportunityItemService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl DealModule {
    /// Create a new module builder
    pub fn builder() -> DealModuleBuilder {
        DealModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_campaign_routes,
            create_opportunity_routes,
            create_opportunity_item_routes,
        };

        Router::new()
            .merge(create_campaign_routes(self.campaign_service.clone()))
            .merge(create_opportunity_routes(self.opportunity_service.clone()))
            .merge(create_opportunity_item_routes(self.opportunity_item_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for DealModule
pub struct DealModuleBuilder {
    db_pool: Option<PgPool>,
}

impl DealModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<DealModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Campaign service
        let campaign_repository = Arc::new(CampaignRepository::new(db_pool.clone()));
        let campaign_service = Arc::new(CampaignService::with_repository(campaign_repository.clone()));

        // Opportunity service
        let opportunity_repository = Arc::new(OpportunityRepository::new(db_pool.clone()));
        let opportunity_service = Arc::new(OpportunityService::with_repository(opportunity_repository.clone()));

        // OpportunityItem service
        let opportunity_item_repository = Arc::new(OpportunityItemRepository::new(db_pool.clone()));
        let opportunity_item_service = Arc::new(OpportunityItemService::with_repository(opportunity_item_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(DealModule {
            campaign_service,
            opportunity_service,
            opportunity_item_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for DealModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
